### PR TITLE
Delete user account from user area

### PR DESCRIPTION
**Pull request by EnragedWildkin**

### CODE REVIEW

**Comment by EnragedWildkin** [comment]
Please do not merge until https://github.com/Vizzuality/i2i/pull/512 is merged

**! important** 
Need to update staging and production ENV variables in order to have publish and delete from Carto features working as expected:
`FSP_CARTO_API_KEY`
`FSP_CARTO_ACCOUNT`
`FSP_CARTO_TABLE`

**Comment by davidsingal** [comment]
We are already using `FSP_CARTO_API_KEY `, could you use `FSP_UPLOAD_API_KEY ` instead, please?

**Comment by EnragedWildkin** [comment]
Do we need separate one for upload? Can we use the old `FSP_CARTO_API_KEY` variable, just update it on staging?

**Comment by davidsingal** [comment]
Yes, we do. The old one will change his permissions.

**Comment by EnragedWildkin** [comment]
Changed to `FSP_CARTO_UPLOAD_API_KEY`.

Currently upload & removal require this variables to work:
`FSP_CARTO_UPLOAD_API_KEY`
`FSP_CARTO_ACCOUNT`
`FSP_CARTO_TABLE`

**Pull request merged**
