### PR TITLE
Adds Community page content

### PR DESCRIPTION
**Pull request by andresgnlez**
Pivotal task: https://www.pivotaltracker.com/story/show/141391639

This PR adds content to Community page based on https://github.com/michaeldssnts/Portal_pages/blob/master/Community.php

### CODE REVIEW

**Comment by clementprdhomme** [comment]
I think my first comment is fixed in #68, isn't it?

**Comment by andresgnlez** [comment]
@clementprdhomme that's it :D

**Comment by andresgnlez** [comment]
`2. The link should encapsulate the content of the card (the image included if you want). Right now, its content is empty and thus a screen reader wouldn't read anything.`

I'll need to merge first https://github.com/Vizzuality/i2i/pull/68 before start working on this.

**Comment by clementprdhomme** [comment]
Done.

**Pull request merged**
